# Generated by Django 3.1.6 on 2021-07-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
